from time import time

from utility.printable import Printable

class Block(Printable):
    """un seul block notre blockchain.
    
    Attributes:
        :index: L'index de ce bloc.
        :previous_hash: Le hachage du bloc précédent dans la blockchain.
        :timestamp: The timestamp of the block (automatically generated by default).
        :transactions: L'horodatage du bloc (généré automatiquement par défaut).
        :proof: Le numéro de preuve de travail qui a donné ce bloc.
    """
    def __init__(self, index, previous_hash, transactions, proof, time=time()):
        self.index = index
        self.previous_hash = previous_hash
        self.timestamp = time
        self.transactions = transactions
        self.proof = proof


